#!/bin/bash
git submodule update --init --recursive && \
rm -rf _site && docker build --platform linux/amd64 -t ai-gh-ai . && \
docker run \
  --rm \
  --platform \
  linux/amd64 \
  -p 4000:4000 \
  -v "$(pwd):/srv/jekyll" \
    ai-gh-ai jekyll serve --host 0.0.0.0